backend:
  name: github
  repo: Wadoohb/libreria
  branch: main

local_backend: false

media_folder: "images/uploads"

collections:
  - name: "libros"
    label: "Libros"
    folder: "_libros"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "autor", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen", name: "imagen", widget: "image" }